/**
 * Searchable list of US universities commonly associated with Greek life.
 * Used for the autocomplete dropdown so typos don't break the search.
 */

export const UNIVERSITIES = [
  "Washington and Lee University",
  "University of Alabama",
  "University of Georgia",
  "University of Mississippi",
  "University of Virginia",
  "University of Texas at Austin",
  "University of North Carolina at Chapel Hill",
  "University of South Carolina",
  "University of Tennessee",
  "University of Florida",
  "University of Arkansas",
  "University of Kentucky",
  "University of Missouri",
  "Louisiana State University",
  "Auburn University",
  "Clemson University",
  "Texas A&M University",
  "Vanderbilt University",
  "Southern Methodist University",
  "Texas Christian University",
  "Baylor University",
  "Tulane University",
  "University of Richmond",
  "Wake Forest University",
  "Duke University",
  "Emory University",
  "Georgia Institute of Technology",
  "Virginia Tech",
  "James Madison University",
  "College of Charleston",
  "Furman University",
  "Sewanee: The University of the South",
  "Rhodes College",
  "Hampden-Sydney College",
  "Davidson College",
  "University of the South",
  "Lehigh University",
  "Bucknell University",
  "Colgate University",
  "Lafayette College",
  "Gettysburg College",
  "Villanova University",
  "Penn State University",
  "University of Michigan",
  "Ohio State University",
  "Indiana University",
  "Purdue University",
  "University of Wisconsin-Madison",
  "University of Iowa",
  "University of Illinois Urbana-Champaign",
  "Northwestern University",
  "University of Minnesota",
  "University of Nebraska-Lincoln",
  "University of Colorado Boulder",
  "University of Oregon",
  "University of Washington",
  "University of Arizona",
  "Arizona State University",
  "University of Southern California",
  "University of California, Los Angeles",
  "University of California, Berkeley",
  "University of California, Santa Barbara",
  "Stanford University",
  "San Diego State University",
  "University of Miami",
  "Florida State University",
  "University of Central Florida",
  "Georgia Southern University",
  "Appalachian State University",
  "East Carolina University",
  "University of Delaware",
  "University of Maryland",
  "University of Connecticut",
  "Boston College",
  "Boston University",
  "Syracuse University",
  "Cornell University",
  "Dartmouth College",
  "University of Pennsylvania",
  "Princeton University",
  "Yale University",
  "Harvard University",
  "Brown University",
  "Columbia University",
  "Georgetown University",
  "George Washington University",
  "American University",
  "University of Denver",
  "Colorado State University",
  "Texas Tech University",
  "Oklahoma State University",
  "University of Oklahoma",
  "University of Kansas",
  "Mississippi State University",
  "University of Alabama at Birmingham",
  "Samford University",
  "Mercer University",
  "Wofford College",
  "Elon University",
  "High Point University",
  "Christopher Newport University",
  "Old Dominion University",
  "William & Mary",
  "University of South Alabama",
  "Troy University",
  "University of North Texas",
  "Stephen F. Austin State University",
  "Sam Houston State University",
  "Coastal Carolina University",
  "Francis Marion University",
  "The Citadel",
  "Virginia Military Institute",
  "Rose-Hulman Institute of Technology",
  "Rensselaer Polytechnic Institute",
  "Worcester Polytechnic Institute",
  "Stevens Institute of Technology",
  "Drexel University",
  "University of Tulsa",
  "Creighton University",
  "Marquette University",
  "DePauw University",
  "Wabash College",
  "Centre College",
  "Transylvania University",
  "Millsaps College",
  "Southwestern University",
  "Trinity University",
  "University of the Pacific",
  "Chapman University",
  "Pepperdine University",
  "Loyola Marymount University",
  "Santa Clara University",
];

/**
 * Search universities by query string. Fuzzy-ish matching:
 * checks if all query words appear in the university name (case-insensitive).
 */
export function searchUniversities(query: string): string[] {
  if (!query.trim()) return UNIVERSITIES;

  const words = query.toLowerCase().split(/\s+/).filter(Boolean);
  return UNIVERSITIES.filter((uni) => {
    const lower = uni.toLowerCase();
    return words.every((w) => lower.includes(w));
  });
}
